accounts/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.register, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('reset_password/', auth_views.PasswordResetView.as_view(html_email_template_name='registration/password_reset_email.html', success_url=reverse_lazy("accounts:password_reset_done")),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password_change/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy("accounts:password_reset_complete")), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

core/urls.py
from django.urls import path
from .views import AboutPageView, FAQPageView, HowItWorksPageView, PrivacyPolicyPageView, contactPageView, dashBoardView, deleteImageView, imageUploadView, userProfileView

app_name = 'core'

urlpatterns = [
    path('', dashBoardView,  name='dashboard'),
    path('my-profile/', userProfileView, name='profile'),
    path('my-favicons/', imageUploadView, name='upload'),
    path('delete/<int:pk>/', deleteImageView, name='delete-favicon'),
    path('contact/', contactPageView, name='contact'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('faq/', FAQPageView.as_view(), name='faq'),
    path('how-it-works/', HowItWorksPageView.as_view(), name='how-it-works'),
    path('privacy-policy/', PrivacyPolicyPageView.as_view(), name='privacy-policy'),
]

favicon_gen/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),
    path('accounts/', include('accounts.urls'), name='accounts'),

    #Django AllAuth
    path('accounts/', include('allauth.urls')),
]

iconator/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from accounts.models import CustomUser


class Image(models.Model):
    user_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    image_name = models.CharField(max_length=50)
    image_url = models.TextField()
    image_upload_date = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ('-image_upload_date',)

    def __str__(self):
        return self.image_name


class Favicon_Zip(models.Model):
    user_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    image_id = models.OneToOneField(Image, on_delete=models.CASCADE)
    favicon_name = models.CharField(max_length=50)
    favicon_zip_url = models.TextField()
    favicon_creation_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.favicon_name

core/views.py
import secrets
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from .engine import createFavicons
from .models import Image, Favicon_Zip
from accounts.models import CustomUser
from django.http import HttpResponseRedirect


def dashBoardView(request):
    return render(request, 'core/dashboard.html')


@login_required
def imageUploadView(request):
    images = Image.objects.filter(user_id=request.user)
    imgs = []
    for image in images:
        favicon = Favicon_Zip.objects.get(image_id=image)
        img = {"image": image, "favicon": favicon}
        imgs.append(img)
    if request.method == 'POST':
        list(messages.get_messages(request))
        try:
            image = request.FILES['image'] or request.POST['image']
            imgid = f'{request.user}_image-{secrets.token_urlsafe(10)}'
            zipid = f'{request.user}_favicon-{secrets.token_urlsafe(10)}'
            url_list = createFavicons(image, imgid, zipid)
            res_img, res_zip = url_list.values()
            image = Image.objects.create(
                user_id=request.user, image_name=imgid, image_url=res_img
            )
            image.save()
            favicon = Favicon_Zip.objects.create(
                user_id=request.user, image_id=image, favicon_name=zipid, favicon_zip_url=res_zip
            )
            favicon.save()
            return redirect('core:upload')
        except:
            messages.info(request, 'Image not provided')
            return render(request, 'core/upload.html', {'images': imgs})
    else:
        return render(request, 'core/upload.html', {'images': imgs})


@login_required
def userProfileView(request):
    images = Image.objects.filter(user_id=request.user)
    imgs = []
    for image in images:
        favicon = Favicon_Zip.objects.get(image_id=image)
        img = {"image": image, "favicon": favicon}
        imgs.append(img)
    if request.method == 'POST':
        list(messages.get_messages(request))
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        if username != request.user.username and CustomUser.objects.filter(username=username).exists():
            messages.info(request, 'Username Taken')
            return redirect('core:profile')
        elif email != request.user.email and CustomUser.objects.filter(email=email).exists():
            messages.info(request, 'Email address already exists')
            return redirect('core:profile')
        else:
            user = CustomUser.objects.get(id=request.user.id)
            user.first_name = first_name
            user.last_name = last_name
            user.username = username
            user.email = email
            if request.FILES:
                profile_pic = request.FILES['new_image']
                user.profile_pic = profile_pic
            user.save()
            messages.success(request, 'Profile Updated Successfully')
            return redirect('core:profile')
    else:
        return render(request, 'core/user_profile.html', {'images': imgs})


@login_required
def deleteImageView(request, pk):
    image = Image.objects.get(id=pk)
    image.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))



def contactPageView(request):
    if request.method == 'POST':
        list(messages.get_messages(request))
        name = request.POST['name']
        email = request.POST['email']
        message = request.POST['message']
        if name and email and message:
            subject = "Website Inquiry"
            body = {
                'Name': f"Hi, I'm {name} and my email is {email}",
                'Message': f'{message}'
            }
            message = "\n\n".join(body.values())
            try:
                send_mail(subject, message, 'iconatorfavicon65@gmail.com', [
                          'iconatorfavicon65@gmail.com'])
                messages.success(request, 'Message Sent')
                return redirect('core:contact')
            except BadHeaderError:
                messages.info(request, 'Invalid Header Found')
                return redirect('core:contact')
    else:
        return render(request, 'core/contact.html')


class AboutPageView(TemplateView):
    template_name = "core/about.html"


class FAQPageView(TemplateView):
    template_name = "core/faq.html"


class HowItWorksPageView(TemplateView):
    template_name = "core/how_it_works.html"


class PrivacyPolicyPageView(TemplateView):
    template_name = "core/privacy_policy.html"

templates/core/about.html
{% extends 'base.html' %}
{% load static %}
{% block custom_style %}
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
{% endblock custom_style %}
{% block title %}
    ICONATOR | ABOUT US
{% endblock title %}
{% block content %}
<main class="about_container">
    <div class="about_heading_container">
        <h1 class="about_header1">About Us</h1>
        <img src="{% static 'images/about_design2.svg' %}" alt="about_design.svg" class="about_header_img" />
    </div>
    <section class="about_section about_sec1">
        <div class="about_sec1_group">
            <h2 class="about_header2">Who We Are</h2>
            <p class="about_sec1_text">
                We are designers, developers and engineers. We believe that from
                quality comes the best.
            </p>
            <p class="about_sec1_text">
                At Iconator, we make the most unfortable experiences in life by
                providing a product and service that offers a complete range of
                features which best serves our customer’s needs.
            </p>
            <p class="about_sec1_text">
                We’re thinking deeply not only to attune our customer’s needs and
                expectations but to seek how, learn and strive for personal and
                professional growth.
            </p>
            <p class="about_sec1_text">
                We make an effort with a passion and commitment to helping you and
                others to bring their vision to life.
            </p>
        </div>
        <div class="about_spirit_img_container">
            <img class="about_spirit_img" src="{% static 'images/about_spirit.png' %}" alt="team_spirit.svg"/>
        </div>
    </section>
    <div class="about_unique_reality">
        <div class="about_unique_reality_text">
            <p class="about_unique_text">Our mission is to provide a</p>
            <strong class="about_unique_text_strong">Unique</strong>
            <p class="about_unique_text">way to turn you vision into</p>
            <strong class="about_unique_text_strong">Reality</strong>
        </div>
    </div>
    <section>
        <h2 class="about_header2">Our Values</h2>
        <div class="about_section">
            <img src="{% static 'images/about_work.png' %}" alt="team_work.png" class="about_work_img" />
            <div class="about_sec2">
                <div class="about_sec2_cont1">
                    <h3 class="about_text_header3">We are Teamwork</h3>
                    <p class="about_sec2_text">
                        With empathy and humility, we seek win-for-all solutions by working
                        together across boundaries, to meet the needs of our customers.
                    </p>
                </div>
                <div class="about_sec2_cont2">
                    <h3 class="about_text_header3">We Innovate</h3>
                    <p class="about_sec2_text">
                        A culture of innovation and continous improvement, we seek the facts
                        and provide insights to help us develop a product that best serve our
                        customer’s needs.
                    </p>
                </div>
                <div class="about_sec2_cont3">
                    <h3 class="about_text_header3">Quantity</h3>
                    <p class="about_sec2_text">
                        We do well to provide an outstanding product and service that
                        together, deliver premium value to our customers.
                    </p>
                </div>
                <div class="about_sec2_cont4">
                    <h3 class="about_text_header3">We are Diverse</h3>
                    <p class="about_sec2_text">
                        Attract, develop and grow talents that reflect the full diversity,
                        inclusion and belonging of society.
                    </p>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock content %}

templates/core/favicon_download.html
{% extends "base.html" %}
{% block content %}
    <section class="text-gray-600 body-font overflow-hidden">
        <a href="{% url 'core:image-list' %}" class="text-xl text-gray-500 capitalize font-semibold hover:underline">back to favicons</a>
        <div class="container px-5 py-24 mx-auto">
            <div class="lg:w-4/5 mx-auto flex flex-wrap">
                <img alt="{{ favicon.favicon_name }}" class="lg:w-1/2 w-full lg:h-auto h-[600px] object-cover object-center rounded" src="{{ image.image_url }}">
                <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
                    <h2 class="text-sm title-font text-gray-500 tracking-widest">FAVVY GEN</h2>
                    <h1 class="text-gray-900 text-3xl title-font font-medium mb-1">{{ favicon.favicon_name }}</h1>
                    <div class="flex mb-4">
                        <span class="flex items-center">
                            <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                                <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
                            </svg>
                            <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                                <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
                            </svg>
                            <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                                <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
                            </svg>
                            <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                                <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
                            </svg>
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                                <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
                            </svg>
                            <span class="text-gray-600 ml-3">4 Reviews</span>
                        </span>
                        <span class="flex ml-3 pl-3 py-2 border-l-2 border-gray-200 space-x-2s">
                            <a class="text-gray-500">
                                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                                    <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
                                </svg>
                            </a>
                            <a class="text-gray-500">
                                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                                    <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
                                </svg>
                            </a>
                            <a class="text-gray-500">
                                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                                    <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                                </svg>
                            </a>
                        </span>
                    </div>
                    <p class="leading-relaxed"></p>
                    <div class="flex mt-6 items-center pb-5 border-b-2 border-gray-100 mb-5">
                        <div class="flex">
                            <span class="mr-3">Color</span>
                            <button class="border-2 border-gray-300 rounded-full w-6 h-6 focus:outline-none"></button>
                            <button class="border-2 border-gray-300 ml-1 bg-gray-700 rounded-full w-6 h-6 focus:outline-none"></button>
                            <button class="border-2 border-gray-300 ml-1 bg-indigo-500 rounded-full w-6 h-6 focus:outline-none"></button>
                        </div>
                        <div class="flex ml-6 items-center">
                            <span class="mr-3">Size</span>
                            <div class="relative">
                                <select class="rounded border appearance-none border-gray-300 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-200 focus:border-indigo-500 text-base pl-3 pr-10">
                                    <option>SM</option>
                                    <option>M</option>
                                    <option>L</option>
                                    <option>XL</option>
                                </select>
                                <span class="absolute right-0 top-0 h-full w-10 text-center text-gray-600 pointer-events-none flex items-center justify-center">
                                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4" viewBox="0 0 24 24">
                                        <path d="M6 9l6 6 6-6"></path>
                                    </svg>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="flex">
                        <span class="title-font font-medium text-2xl text-gray-900">$58.00</span>
                        <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"><a href="{{ favicon.favicon_zip_url }}" download>Download Favicon</a></button>
                        <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"><a href="{% url 'core:delete-favicon' image.pk %}">Delete Favicon</a></button>
                        <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
                            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                                <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
                            </svg>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

templates/core/upload.html
{% extends "base.html" %}
{% load static %}
{% block custom_style %}
    <link rel="stylesheet" href="{% static 'css/upload.css' %}">
{% endblock custom_style %}
{% block title %}
    ICONATOR | UPLOAD
{% endblock title %}
{% block content %}
<section class="section_center">
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'info' %}
                <div class="alert_message alert_danger">
                    <strong>{{ message }}</strong>
                </div>
            {% elif message.tags == 'success' %}
                <div class="alert_message alert_success">
                    <strong>{{ message }}</strong>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <form action="" method="post" class="upload_form" enctype="multipart/form-data" onsubmit="isUploading()">
        <h1>Create a new favicon</h1>
        {% csrf_token %}
        <label for="imageForm" class="upload_label">
            <img src="{% static 'images/form_icon.svg' %}" alt="form icon" />
            <p>Click / Drag and Drop to Upload</p>
            <input type="file" name="image" id="imageForm" />
        </label>
        <div class="preview_upload">
            <figure class="preview_img"></figure>
            <button type="submit" class="btn_gold">upload</button>
            <span class="isUploading"><i class="fa-solid fa-spinner"></i></span>
        </div>
    </form>
    <span class="info">upload an image/icon in (PNG, JPG, WEB) and convert to usable favicons (ICO)</span>
</section>
<section class="section_center favicons">
    <h1 class="list_text">my favicons</h1>
    <div class="favicons_list">
        {% for image in images %}
            <article class="favicon">
                <figure class="favicon_img">
                    <img src="{{ image.image.image_url }}" alt="{{ image.image.image_name }}" />
                </figure>
                <div class="favicon_info">
                    <h2>{{ image.image.image_name }}</h2>
                    <div class="btns">
                        <button class="btn_gold">
                            <a href="{{ image.favicon.favicon_zip_url }}" download>download <img class="btn_icon" src="{% static 'images/download_icon.svg' %}" alt="download icon" /></a>
                        </button>
                        <button class="btn_gold">
                            <a href="{% url 'core:delete-favicon' image.image.pk %}">delete <img class="btn_icon" src="{% static 'images/delete_icon.svg' %}" alt="delete icon" /></a>
                        </button>
                    </div>
                </div>
            </article>
        {% endfor %}
        <figure class="style_icon">
            <img src="{% static 'images/arrow_icon.svg' %}" alt="arrow_icon" />
        </figure>
    </div>
</section>
<section class="section_center">
    <div class="favicon_instructions">
        <h2>How to use your Favicon</h2>
        <p>
            First, use the download button to download the zip file for your
            favicon, then extract the files. Each zip file contains:
        </p>
        <ul>
            <li>favicon512x512.png</li>
            <li>favicon192x192.png</li>
            <li>favicon180x180.png</li>
            <li>favicon32x32.png</li>
            <li>favicon16x16.png</li>
            <li>favicon.ico</li>
            <li>site.webmanifest</li>
        </ul>
        <p>Then place the files in the root directory of your website.</p>
        <p>
            Next, copy the following link tags and paste them into the head of
            your HTML.
        </p>
        <div class="html_code">
            <code id="copy_text">
                <span>&lt;link rel="apple-touch-icon" sizes="180x180" href="/favicon180x180.png"&gt;</span><br/>
                <span>&lt;link rel="icon" sizes="32x32" href="/favicon32x32.png"&gt;</span><br/>
                <span>&lt;link rel="icon" sizes="16x16" href="/favicon16x16.png"&gt;</span><br/>
                <span>&lt;link rel="manifest" href="/site.webmanifest"&gt;</span>
            </code>
        </div>
        <button class="btn_gold" id="copy_btn">copy</button>
    </div>
</section>
{% endblock content %}
{% block custom_js %}
    <script src="{% static 'js/upload.js' %}"></script>
{% endblock custom_js %}

templates/core/user_profile.html
{% extends "base.html" %}
{% load static %}
{% block custom_style %}
    <link rel="stylesheet" href="{% static 'css/user_profile.css' %}">
{% endblock custom_style %}
{% block title %}
    ICONATOR | MY ACCOUNT
{% endblock title %}
{% block content %}
    <main>
        <div class="user_banner_container" role="banner">
            <h1>User Profile</h1>
        </div>
        <section class="user_section_container">
            <section class="user_section_top">
                <div class="user_details">
                    {% if request.user.profile_pic %}
                    <figure class="user_img">
                        <img src="{{ request.user.profile_pic.url }}" alt="{{ request.user.first_name }}" />
                        <label for="new_image" class="edit_pen"><i class="fa-solid fa-file-pen"></i><input type="file" name="new_image" id="new_image" form="edit_form"></label>
                    </figure>
                    {% else %}
                    <div class="user_img">
                        <div class="default_user_img">{{ request.user.username.0 }}</div>
                        <label for="new_image" class="edit_pen"><i class="fa-solid fa-file-pen"></i><input type="file" name="new_image" id="new_image" form="edit_form"></label>
                    </div>
                    {% endif %}
                    <div class="user_info">
                        <p class="user_fullname">{{ request.user.first_name }} {{ request.user.last_name }}</p>
                        <p class="user_username">@{{ request.user.username }}</p>
                    </div>
                </div>
                <div class="edit_user_profile">
                    <img src="{% static 'images/edit_profile_icon.svg' %}" alt="edit icon">
                    <span class="edit_profile">edit profile</span>
                </div>
            </section>
            <section class="user_section_middle">
                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'info' %}
                            <div class="alert_message alert_danger">
                                <strong>{{ message }}</strong>
                            </div>
                        {% elif message.tags == 'success' %}
                            <div class="alert_message alert_success">
                                <strong>{{ message }}</strong>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <h1 class="user_list_text">my history</h1>
                <div class="user_favicons_list">
                    {% for image in images %}
                    <article class="user_favicon">
                        <figure class="user_favicon_img">
                            <img src="{{ image.image.image_url }}" alt="{{ image.image.image_name }}" />
                        </figure>
                        <div class="user_favicon_info">
                            <h2>{{ image.image.image_name }}</h2>
                            <div class="user_btns">
                                <button class="user_btn">Copy HTML code <img class="user_btn_icon" src="{% static 'images/edit_icon.svg' %}" alt="download icon"></button>
                                <span class="favicon_date" data-date='{{ image.image.image_upload_date }}'></span>
                            </div>
                        </div>
                        <button class="user_options"><i class="fa-solid fa-ellipsis-vertical"></i></button>
                        <div class="user_option_list">
                            <button class="user_option_item"><a href="{{ image.favicon.favicon_zip_url }}" download>download</a></button>
                            <button class="user_option_item"><a href="{% url 'core:delete-favicon' image.image.pk %}">delete</a></button>
                        </div>
                    </article>
                    {% endfor %}
                </div>
            </section>
            <section class="user_section_bottom">
                <h1>account info</h1>
                <div class="user_account_info">
                    <div class="user_account_info_item">
                        <p>First Name : <span class="user_account_info_item_value">{{ request.user.first_name }}</span></p>
                    </div>
                    <div class="user_account_info_item">
                        <p>Last Name : <span class="user_account_info_item_value">{{ request.user.last_name }}</span></p>
                    </div>
                    <div class="user_account_info_item">
                        <p>username : <span class="user_account_info_item_value">{{ request.user.username }}</span></p>
                    </div>
                    <div class="user_account_info_item">
                        <p>Email : <span class="user_account_info_item_value">{{ request.user.email }}</span></p>
                    </div>
                </div>
                <button class="user_action_btn"><a href="{% url 'accounts:logout' %}">logout</a></button>
            </section>
            <section class="edit_profile_display">
                <form action="" method="post" id="edit_form" class="edit_form" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1>edit details</h1>
                    <label>First Name<input type="text" name="first_name" value="{{ request.user.first_name }}" class="form-input" /></label>
                    <label>Last Name<input type="text" name="last_name" value="{{ request.user.last_name }}" class="form-input" /></label>
                    <label>Username<input type="text" name="username" value="{{ request.user.username }}" class="form-input" /></label>
                    <label>Enter Email Address<input type="email" name="email" value="{{ request.user.email }}" class="form-input" /></label>
                    <div class="edit_actions">
                        <button class="user_action_btn edit_btn" type="submit">Edit</button>
                        <p class="reset_password"><a href="{% url 'accounts:reset_password' %}">Reset password</a></p>
                    </div>
                </form>
                <figure class="edit_hero_image"><img src="{% static 'images/edit_page_hero_img.png' %}" alt="hero image"></figure>
            </section>
        </section>
    </main>
{% endblock %}
{% block custom_js %}
    <script src="{% static 'js/profile.js' %}"></script>
{% endblock custom_js %}