accounts/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.register, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('reset_password/', auth_views.PasswordResetView.as_view(html_email_template_name='registration/password_reset_email.html', success_url=reverse_lazy("accounts:password_reset_done")),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password_change/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy("accounts:password_reset_complete")), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

core/urls.py
from django.urls import path
from .views import AboutPageView, FAQPageView, HowItWorksPageView, PrivacyPolicyPageView, contactPageView, dashBoardView, deleteImageView, imageUploadView, userProfileView

app_name = 'core'

urlpatterns = [
    path('', dashBoardView,  name='dashboard'),
    path('my-profile/', userProfileView, name='profile'),
    path('my-favicons/', imageUploadView, name='upload'),
    path('delete/<int:pk>/', deleteImageView, name='delete-favicon'),
    path('contact/', contactPageView, name='contact'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('faq/', FAQPageView.as_view(), name='faq'),
    path('how-it-works/', HowItWorksPageView.as_view(), name='how-it-works'),
    path('privacy-policy/', PrivacyPolicyPageView.as_view(), name='privacy-policy'),
]

favicon_gen/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),
    path('accounts/', include('accounts.urls'), name='accounts'),

    #Django AllAuth
    path('accounts/', include('allauth.urls')),
]

iconator/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- FONT -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;700;800" />
    <!-- FONT AWESOME ICONS INCASE WE NEED THEM -->
    <script src="https://kit.fontawesome.com/5ca15c60cd.js" crossorigin="anonymous"></script>
    <!-- STYLESHEET -->
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/header&footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/messages.css' %}">
    {% block custom_style %}
    {% endblock custom_style %}
    <!-- FAVICON -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon180x180.png' %}">
    <link rel="icon" sizes="32x32" href="{% static 'images/favicon32x32.png' %}">
    <link rel="icon" sizes="16x16" href="{% static 'images/favicon16x16.png' %}">
    <link rel="manifest" href="{% static 'images/site.webmanifest' %}">
    <!-- TITLE -->
    <title>
        {% block title %}
        {% endblock title %}
    </title>
</head>
<body class="mx-auto bg-blue-50 min-h-screen">
    {% include "navbar.html" %}
    {% block content %}
    {% endblock content %}
    {% include 'footer.html' %}
    {% block custom_js %}
    {% endblock custom_js %}
    <script src="{% static 'js/header_footer.js' %}"></script>
    <script>
        const messages = document.querySelector('.alert_message');
        if (messages) {
            setTimeout(() => {
                messages.classList.add('message_fade_out');
                setTimeout(() => {
                    messages.style.visibility = 'hidden';
                }, 500);
            }, 4000);
        }
    </script>
</body>
</html>

templates/base_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- STYLESHEET -->
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/header&footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/messages.css' %}">
    {% block custom_style %}
    {% endblock custom_style %}
    <!-- FAVICON -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon180x180.png' %}">
    <link rel="icon" sizes="32x32" href="{% static 'images/favicon32x32.png' %}">
    <link rel="icon" sizes="16x16" href="{% static 'images/favicon16x16.png' %}">
    <link rel="manifest" href="{% static 'images/site.webmanifest' %}">
    <!-- TITLE -->
    <title>
        {% block title %}
        {% endblock title %}
    </title>
</head>
<body class="mx-auto bg-blue-50 min-h-screen">
    {% include "navbar.html" %}
    {% block content %}
    {% endblock content %}
    {% include 'footer.html' %}
    {% block custom_js %}
    {% endblock custom_js %}
    <script src="{% static 'js/header_footer.js' %}"></script>
    <script>
        const messages = document.querySelector('.alert_message');
        if (messages) {
            setTimeout(() => {
                messages.classList.add('message_fade_out');
                setTimeout(() => {
                    messages.style.visibility = 'hidden';
                }, 500);
            }, 4000);
        }
    </script>
</body>
</html>

templates/footer.html
{% load static %}
<footer id="footer">
	<section class="first-section">
		<div class="footer_cards">
			<h1>Product</h1>
			<ul class="footer_card_items">
				<li><a href="{% url 'core:upload' %}">Favicon Generator</a></li>
				<li>Favicons for good web starters</li>
				<li>HTML Code Download</li>
			</ul>
		</div>
		<div class="footer_cards">
			<h1>Company</h1>
			<ul class="footer_card_items">
				<li><a href="{% url 'core:about' %}">About</a></li>
				<li><a href="https://github.com/zuri-training/Team-65-Favicon-gen/blob/dev/documentation/Team.md">Our Team</a></li>
				<li><a href="{% url 'core:privacy-policy' %}">Privacy Policy</a></li>
			</ul>
		</div>
		<div class="footer_cards">
			<h1>Help & Support</h1>
			<ul class="footer_card_items">
				<li>Iconator Community</li>
				<li><a href="{% url 'core:faq' %}">FAQs</a></li>
				<li><a href="{% url 'core:contact' %}">Report Bug</a></li>
			</ul>
		</div>
		<div class="footer_cards">
			<h1>Contact Us</h1>
			<ul class="footer_card_items">
				<li>iconator@gmail.com</li>
				<li>(+234) 804 6709 389</li>
				<li>24, Idowu Martins Street, Ikeja Lagos</li>
				<li>
					<div class="footer_social_icons">
						<img src="{% static 'images/facebook_icon.svg' %}" alt="facebook-icon" />
						<img src="{% static 'images/instagram_icon.svg' %}" alt="instagram-icon" />
						<img src="{% static 'images/twitter_icon.svg' %}" alt="twitter-icon" />
						<img src="{% static 'images/youtube_icon.svg' %}" alt="youtube-icon" />
					</div>
				</li>
			</ul>
		</div>
	</section>
	<section class="footer_subsection">
		<div class="footer_select_container">
			<select name="lang" id="footer_lang" class="custom_select">
				<option value="english(us)" checked>English (US)</option>
				<option value="english(us)">English (UK)</option>
				<option value="english(us)">Yoruba</option>
				<option value="english(us)">Igbo</option>
			</select>
		</div>
		<div class="footer_last_section">
			<img src="{% static 'images/logo_2.svg' %}" alt="icon2" />
			<p>&copy;<span class="footer_year"></span> All rights reserved</p>
		</div>
	</section>
</footer>

templates/navbar.html
{% load static %}
<header id="header">
    <a href="{% url 'core:dashboard' %}"><img src="{% static 'images/logo.svg' %}" alt="Iconator" id="icon" /></a>
    <nav class="header_nav">
        <p id="favicon">Favicon <i class="fa-solid fa-sort-down"></i></p>
        <a href="{% url 'core:about' %}"><p>About Us</p></a>
        <p id="help&support">Help & Support <i class="fa-solid fa-sort-down"></i></p>
    </nav>
    {% if request.user.is_authenticated %}
        <a href="{% url 'core:profile' %}">
            <div class="header_user_details">
                {% if request.user.profile_pic %}
                    <figure class="header_user_img"><img src="{{ request.user.profile_pic.url }}" alt="{{ request.user.first_name }}"/></figure>
                {% else %}
                    <div class="header_default_user_img">{{ request.user.username.0 }}</div>
                {% endif %}
                <div class="header_user_info">
                    <p class="header_fullname">{{ request.user.first_name }} {{ request.user.last_name }} <i class="fa-solid fa-sort-down"></i></p>
                    <p class="header_username">@{{ request.user.username }} <span class="header_active_notification"></span></p>
                </div>
            </div>
        </a>
    {% else %}
        <div class="header_auth_btns">
            <button class="header_auth_btn"><a href="{% url 'accounts:signup' %}">Sign Up</a></button>
            <button class="header_auth_btn"><a href="{% url 'accounts:login' %}">Sign In</a></button>
        </div>
    {% endif %}
    <button class="header_hamburger"><i class="fa-solid fa-bars"></i></button>
</header>
<div class="header_dropdown_box" data-drop="favicon">
    <div class="header_dropdown_box_item">
        <a href="{% url 'core:upload' %}">Generate Favicon</a>
    </div>
    <div class="header_dropdown_box_item">
        <a href="{% url 'core:how-it-works' %}">How It Works</a>
    </div>
</div>
<div class="header_dropdown_box" data-drop="help&support">
    <div class="header_dropdown_box_item">
        <a href="{% url 'core:contact' %}">Contact Us</a>
    </div>
    <div class="header_dropdown_box_item">
        <a href="{% url 'core:faq' %}">FAQs</a>
    </div>
    <div class="header_dropdown_box_item">
        <a href="{% url 'core:privacy-policy' %}">Privacy Policy</a>
    </div>
</div>
<aside class="header_sidebar">
    <button class="close_sidebar"><i class="fa-solid fa-xmark"></i></button>
    <nav class="header_sidebar_nav">
        {% if request.path == '/' %}
            <p class="active"><a href="{% url 'core:dashboard' %}">Home</a></p>
        {% else %}
            <p><a href="{% url 'core:dashboard' %}">Home</a></p>
        {% endif %}
        {% if 'my-favicons' in request.path %}
            <p class="active"><a href="{% url 'core:upload' %}">Generate Favicon</a></p>
        {% else %}
            <p><a href="{% url 'core:upload' %}">Generate Favicon</a></p>
        {% endif %}
        {% if 'how-it-works' in request.path %}
            <p class="active"><a href="{% url 'core:how-it-works' %}">How It Works</a></p>
        {% else %}
            <p><a href="{% url 'core:how-it-works' %}">How It Works</a></p>
        {% endif %}
        {% if 'about' in request.path %}
            <p class="active"><a href="{% url 'core:about' %}">about us</a></p>
        {% else %}
            <p><a href="{% url 'core:about' %}">about us</a></p>
        {% endif %}
        {% if 'contact' in request.path %}
            <p class="active"><a href="{% url 'core:contact' %}">Contact Us</a></p>
        {% else %}
            <p><a href="{% url 'core:contact' %}">Contact Us</a></p>
        {% endif %}
        {% if 'faq' in request.path %}
            <p class="active"><a href="{% url 'core:faq' %}">FAQ</a></p>
        {% else %}
            <p><a href="{% url 'core:faq' %}">Faq</a></p>
        {% endif %}
        {% if 'privacy-policy' in request.path %}
            <p class="active"><a href="{% url 'core:privacy-policy' %}">Privacy Policy</a></p>
        {% else %}
            <p><a href="{% url 'core:privacy-policy' %}">Privacy Policy</a></p>
        {% endif %}
    </nav>
    {% if request.user.is_authenticated %}
        <a href="{% url 'core:profile' %}">
            <div class="header_user_details">
                {% if request.user.profile_pic %}
                    <figure class="header_user_img"><img src="{{ request.user.profile_pic.url }}" alt="{{ request.user.first_name }}"/></figure>
                {% else %}
                    <div class="header_default_user_img">{{ request.user.username.0 }}</div>
                {% endif %}
                <div class="header_user_info">
                    <p class="header_fullname">{{ request.user.first_name }} {{ request.user.last_name }} <i class="fa-solid fa-sort-down"></i></p>
                    <p class="header_username">@{{ request.user.username }} <span class="header_active_notification"></span></p>
                </div>
            </div>
        </a>
    {% else %}
        <div class="header_auth_btns">
            <button class="header_auth_btn"><a href="{% url 'accounts:signup' %}">Sign Up</a></button>
            <button class="header_auth_btn"><a href="{% url 'accounts:login' %}">Sign In</a></button>
        </div>
    {% endif %}
</aside>